# script arguments

In [ ]:
import sys

# argument list:
# - stemmed: true or false
# - representation: BOW, TFIDF, LDA-10, LDA-25, LDA-50, Word2Vec, Glove, Doc2Vec
# - technique: ball_tree, kd_tree, brute
# - k-neighbors: 5, 10, 20, 40

stemmed = sys.argv[1]
representation = sys.argv[2]
technique = sys.argv[3]
num_neighbors = int(sys.argv[4])

if (stemmed not in ['true', 'false']):
    print('incorrect stemmed argument value: ' + stemmed)
    quit()
    
if (representation not in ['BOW', 'TFIDF', 'LDA_10', 'LDA_25', 'LDA_50', 'Word2Vec', 'Glove', 'Doc2Vec']):
    print('incorrect representation argument value: ' + representatioon)
    quit()
    
if (technique not in ['ball_tree', 'kd_tree', 'brute']):
    print('incorrect knn technique argument value: ' + technique)
    quit()
    
if (num_neighbors not in [5, 10, 20, 40]):
    print('incorrect k-neighbors argument value: ' + num_neighbors)
    quit()

In [1]:
stemmed = 'true'
#representation = 'BOW' # good :)
#representation = 'TFIDF' # 
#representation = 'LDA_10' # good :)
#representation = 'LDA_25' # good :)
#representation = 'LDA_50' # good :)
#representation = 'Word2Vec' # good :)
#representation = 'Glove' # good :)
#representation = 'Doc2Vec' # good :)
technique = 'kd_tree'
num_neighbors = 10

In [10]:
stemmed = 'false'
#representation = 'BOW' # takes too long
#representation = 'TFIDF' #
representation = 'LDA_10' # 
#representation = 'LDA_25' # 
#representation = 'LDA_50' # 
#representation = 'Word2Vec' # 
#representation = 'Glove' # 
#representation = 'Doc2Vec' # 
technique = 'kd_tree'
num_neighbors = 10

In [2]:
from clustering_and_metrics_knn import bow_model, tfidf_model, lda_10_model, lda_25_model, lda_50_model, w2v_model, gv_model, d2v_model
import numpy as np
import pickle
from AppDetexKnnMetricResults import KnnMetricResults

### clustering and metrics methods

In [ ]:
#d2v_knn_inter_dist_sample = [d2v_knn.sample_mean_intercluster_dist(500) for i in range(5)]
#d2v_knn_inter_dist_mean = np.average(d2v_knn_inter_dist_sample)

## creating and saving result object

In [3]:
def calculate_and_save_metrics(knn_results, time_1, time_2):
    # interdistance mean
    knn_results_inter_dist_sample = [knn_results.sample_mean_intercluster_dist(500) for i in range(5)]
    knn_results_inter_dist_mean = np.average(knn_results_inter_dist_sample)
    
    # silhouette coefficient
    a = np.mean(knn_results.intra_avg_list)
    b = knn_results_inter_dist_mean
    silhouette_score = (b - a)/np.max([a, b])

    # creating and saving result object
    knnMetricResults = KnnMetricResults(stemmed, representation, technique, num_neighbors)
    knnMetricResults.set_intra_metrics(knn_results.intra_avg_list, knn_results.intra_variance_list)
    knnMetricResults.set_inter_metrics(knn_results_inter_dist_sample, knn_results_inter_dist_mean)
    knnMetricResults.set_silhouette(silhouette_score)
    
    # set computing time metrics
    time_3 = round(time.time() * 1000)
    knnMetricResults.set_compute_time(time_2-time_1, time_3-time_2)
    
    knnMetricResults.save()

## bag of words

In [8]:
def new_bow_knn():
    bow_knn = bow_model(stemmed, technique, num_neighbors)
    bow_knn.load_data()
    time_1 = round(time.time() * 1000)
    bow_knn.run_knn()
    time_2 = round(time.time() * 1000)
    bow_knn.calculate_intra_average_and_variance()
    bow_knn.generate_index_centroid_map()
    return bow_knn, time_1, time_2

In [9]:
if representation == 'BOW':
    knn_results, time_1, time_2 = new_bow_knn()
    calculate_and_save_metrics(knn_results, time_1, time_2)

using file extension .npz for bow/bow_matrix
loading ../../processed_files/bow/bow_matrix.npz
loading ../../processed_files/df_merged.pickle
finding nearest 10 neighbors with kd_tree algorithm
type of metrix: <class 'scipy.sparse.csr.csr_matrix'>


/Users/dkarsann/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_neighbors=10, radius=kd_tree as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


calculating metrics for intracluster average and variance


## tfidf matrix

In [10]:
def new_tfidf_knn():
    tfidf_knn = tfidf_model(stemmed, technique, num_neighbors)
    tfidf_knn.load_data()
    time_1 = round(time.time() * 1000)
    tfidf_knn.run_knn()
    time_2 = round(time.time() * 1000)
    tfidf_knn.calculate_intra_average_and_variance()
    tfidf_knn.generate_index_centroid_map()
    return tfidf_knn, time_1, time_2

In [11]:
if representation == 'TFIDF':
    knn_results, time_1, time_2 = new_tfidf_knn()
    calculate_and_save_metrics(knn_results, time_1, time_2)

using file extension .npz for tfidf/stemmed_tfidf_matrix
loading ../../processed_files/tfidf/stemmed_tfidf_matrix.npz
loading ../../processed_files/df_merged.pickle
finding nearest 10 neighbors with kd_tree algorithm


/Users/dkarsann/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_neighbors=10, radius=kd_tree as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


calculating metrics for intracluster average and variance


# LDA

## lda 10 matrix

In [11]:
def new_lda_10_knn():
    lda_10_knn = lda_10_model(stemmed, technique, num_neighbors)
    lda_10_knn.load_data()
    time_1 = round(time.time() * 1000)
    lda_10_knn.run_knn()
    time_2 = round(time.time() * 1000)
    lda_10_knn.calculate_intra_average_and_variance()
    lda_10_knn.generate_index_centroid_map()
    return lda_10_knn, time_1, time_2

In [12]:
if representation == 'LDA_10':
    knn_results, time_1, time_2 = new_lda_10_knn()
    calculate_and_save_metrics(knn_results, time_1, time_2)

using file extension .npy for lda_10/lda_10_matrix
loading ../../processed_files/lda_10/lda_10_matrix.npy
loading ../../processed_files/df_merged.pickle
finding nearest 10 neighbors with kd_tree algorithm
type of metrix: <class 'numpy.ndarray'>


/Users/dkarsann/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_neighbors=10, radius=kd_tree as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


calculating metrics for intracluster average and variance


In [11]:
np.any(np.isnan(knn_results.matrix))

False

## lda 25 matrix

In [11]:
def new_lda_25_knn():
    lda_25_knn = lda_25_model(stemmed, technique, num_neighbors)
    lda_25_knn.load_data()
    time_1 = round(time.time() * 1000)
    lda_25_knn.run_knn()
    time_2 = round(time.time() * 1000)
    lda_25_knn.calculate_intra_average_and_variance()
    lda_25_knn.generate_index_centroid_map()
    return lda_25_knn, time_1, time_2

In [13]:
if representation == 'LDA_25':
    knn_results, time_1, time_2 = new_lda_25_knn()
    calculate_and_save_metrics(knn_results, time_1, time_2)

using file extension .npy for lda_25/stemmed_lda_25_matrix
loading ../../processed_files/lda_25/stemmed_lda_25_matrix.npy
loading ../../processed_files/df_merged.pickle
finding nearest 10 neighbors with kd_tree algorithm
type of metrix: <class 'numpy.ndarray'>


/Users/dkarsann/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_neighbors=10, radius=kd_tree as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


calculating metrics for intracluster average and variance


## lda 50 matrix

In [15]:
def new_lda_50_knn():
    lda_50_knn = lda_50_model(stemmed, technique, num_neighbors)
    lda_50_knn.load_data()
    time_1 = round(time.time() * 1000)
    lda_50_knn.run_knn()
    time_2 = round(time.time() * 1000)
    lda_50_knn.calculate_intra_average_and_variance()
    lda_50_knn.generate_index_centroid_map()
    return lda_50_knn, time_1, time_2

In [18]:
if representation == 'LDA_50':
    knn_results, time_1, time_2 = new_lda_50_knn()
    calculate_and_save_metrics(knn_results, time_1, time_2)

using file extension .npy for lda_50/stemmed_lda_50_matrix
loading ../../processed_files/lda_50/stemmed_lda_50_matrix.npy
loading ../../processed_files/df_merged.pickle
finding nearest 10 neighbors with kd_tree algorithm
type of metrix: <class 'numpy.ndarray'>


/Users/dkarsann/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_neighbors=10, radius=kd_tree as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


calculating metrics for intracluster average and variance


## word2vec matrix

In [20]:
def new_w2v_knn():
    w2v_knn = w2v_model(stemmed, technique, num_neighbors)
    w2v_knn.load_data()
    time_1 = round(time.time() * 1000)
    w2v_knn.run_knn()
    time_2 = round(time.time() * 1000)
    w2v_knn.calculate_intra_average_and_variance()
    w2v_knn.generate_index_centroid_map()
    return w2v_knn, time_1, time_2

In [21]:
if representation == 'Word2Vec':
    knn_results, time_1, time_2 = new_w2v_knn()
    calculate_and_save_metrics(knn_results, time_1, time_2)

using file extension .npy for w2v/stemmed_w2v_matrix
loading ../../processed_files/w2v/stemmed_w2v_matrix.npy
loading ../../processed_files/df_merged.pickle
finding nearest 10 neighbors with kd_tree algorithm
type of metrix: <class 'numpy.ndarray'>


/Users/dkarsann/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_neighbors=10, radius=kd_tree as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


calculating metrics for intracluster average and variance


## glove matrix

In [4]:
def new_gv_knn():
    gv_knn = gv_model(stemmed, technique, num_neighbors)
    gv_knn.load_data()
    time_1 = round(time.time() * 1000)
    gv_knn.run_knn()
    time_2 = round(time.time() * 1000)
    gv_knn.calculate_intra_average_and_variance()
    gv_knn.generate_index_centroid_map()
    return gv_knn, time_1, time_2

In [5]:
if representation == 'Glove':
    knn_results, time_1, time_2 = new_gv_knn()
    calculate_and_save_metrics(knn_results, time_1, time_2)

using file extension .npy for glove/stemmed_glove_matrix
loading ../../processed_files/glove/stemmed_glove_matrix.npy
loading ../../processed_files/df_merged.pickle
finding nearest 10 neighbors with kd_tree algorithm
type of metrix: <class 'numpy.ndarray'>


/Users/dkarsann/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_neighbors=10, radius=kd_tree as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


calculating metrics for intracluster average and variance


## doc2vec matrix

In [4]:
def new_d2v_knn():
    d2v_knn = d2v_model(stemmed, technique, num_neighbors)
    d2v_knn.load_data()
    time_1 = round(time.time() * 1000)
    d2v_knn.run_knn()
    time_2 = round(time.time() * 1000)
    d2v_knn.calculate_intra_average_and_variance()
    d2v_knn.generate_index_centroid_map()
    return d2v_knn, time_1, time_2

In [6]:
if representation == 'Doc2Vec':
    knn_results, time_1, time_2 = new_d2v_knn()
    calculate_and_save_metrics(knn_results, time_1, time_2)

using file extension .npy for d2v/stemmed_d2v_matrix
loading ../../processed_files/d2v/stemmed_d2v_matrix.npy
loading ../../processed_files/df_merged.pickle
finding nearest 10 neighbors with kd_tree algorithm
type of metrix: <class 'numpy.ndarray'>


/Users/dkarsann/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_neighbors=10, radius=kd_tree as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


calculating metrics for intracluster average and variance


## metric analysis

### Interdistance mean

In [6]:
knn_results_inter_dist_sample = [knn_results.sample_mean_intercluster_dist(100) for i in range(1)]
knn_results_inter_dist_mean = np.average(knn_results_inter_dist_sample)

In [7]:
knn_results.intra_avg_list

array([0.06195896, 0.        , 0.18693263, ..., 0.        , 0.19070351,
       0.34003941])

### silhouetter coefficient

In [8]:
a = np.average(knn_results.intra_avg_list)
b = knn_results_inter_dist_mean

In [9]:
silhouette_score = (b - a)/np.max([a, b])

# creating and saving result object

In [10]:
import pickle
from AppDetexKnnMetricResults import KnnMetricResults

In [11]:
knnMetricResults = KnnMetricResults(stemmed, representation, technique, num_neighbors)
knnMetricResults.set_intra_metrics(knn_results.intra_avg_list, knn_results.intra_variance_list)
knnMetricResults.set_inter_metrics(knn_results_inter_dist_sample, knn_results_inter_dist_mean)
knnMetricResults.set_silhouette(silhouette_score)

In [12]:
knnMetricResults.dataset

'AppDetex'

In [13]:
knnMetricResults.strategy

'Knn'

In [14]:
knnMetricResults.stemmed

'true'

In [15]:
knnMetricResults.representation

'LDA_10'

In [16]:
knnMetricResults.technique

'kd_tree'

In [17]:
knnMetricResults.num_neighbors

10

In [18]:
knnMetricResults.filename

'../../../results/AppDetex_Knn_true_LDA_10_kd_tree_10.metrics'

In [19]:
knnMetricResults.intra_average

array([0.06195896, 0.        , 0.18693263, ..., 0.        , 0.19070351,
       0.34003941])

In [20]:
knnMetricResults.intra_variance

array([0.00683871, 0.        , 0.00601564, ..., 0.        , 0.0046002 ,
       0.03060874])

In [21]:
knnMetricResults.inter_distance_sample

[0.7921576060777858]

In [22]:
knnMetricResults.inter_distance_mean

0.7921576060777858

In [23]:
knnMetricResults.silhouette

0.8680048092274136

In [24]:
knnMetricResults.save()